# KNN 

## using classification(0/1)

In [1]:
import pandas as pd

df = pd.DataFrame({
    'attendance': [90, 85, 70, 95, 60],
    'assignment': [88, 75, 65, 92, 58],
    'exam': [85, 72, 60, 95, 55],
    'success': [1, 1, 0, 1, 0]
})

df

,attendance,assignment,exam,success
0,90,88,85,1
1,85,75,72,1
2,70,65,60,0
3,95,92,95,1
4,60,58,55,0


In [2]:
x = df[['attendance', 'assignment', 'exam']]
y = df['success']

In [3]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors = 3)
model.fit(x,y) 

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",3
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


In [4]:
new_data = pd.DataFrame({
    'attendance': [60],
    'assignment': [50],
    'exam': [55],
})

model.predict(new_data) 

array([0])

In [5]:
import numpy as np
A=[2,4,6]
B=[1,3,5]

dist = np.sqrt(sum((a-b)**2 for a,b in zip(A,B)))
print(dist)

1.7320508075688772


In [6]:
a = float(input("Enter value"))
b = float(input("Enter value"))
c = float(input("Enter value"))
d = float(input("Enter value"))

dist = np.sqrt((a-b)**2 + (c-d)**2)
dist


Enter value 1
Enter value 2
Enter value 3
Enter value 4


np.float64(1.4142135623730951)

In [7]:
data = pd.DataFrame({
    'heighte(cm)' : [150, 155, 160, 170, 175],
    'class' : [0,0,0,1,1] # 0-short,  1 -tall
})

data

,heighte(cm),class
0,150,0
1,155,0
2,160,0
3,170,1
4,175,1


In [8]:
# k = 3

# new person -- 165

# 165-150 = 15
# 165-155 = 10
# 165-160 = 5
# 165-170 = 5
# 165-175 = 10 


## using regression

## predict car price based on car age 

In [11]:
import pandas as pd
data={
    'car age' : [1,2,3,4,5,6,7],
    'car price(lakhs)' : [12,11,9.5,8,7,6,5]
}

car = pd.DataFrame(data)
car.head(2) 

,car age,car price(lakhs)
0,1,12.0
1,2,11.0


In [12]:
x = car[['car age']]
y = car['car price(lakhs)'] 

In [13]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [14]:
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor(n_neighbors = 1)
model.fit(x_train,y_train) 

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",1
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Uniform weights are used by default.See the following example for a demonstration of the impact ofdifferent weighting schemes on predictions::ref:`sphx_glr_auto_examples_neighbors_plot_regression.py`.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this isequivalent to using manhattan_distance (l1), and euclidean_distance(l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.",2
,"metric metric: str, DistanceMetric object or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.If metric is a DistanceMetric object, it will be passed directly tothe underlying computation routines.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


In [25]:
y_pred = model.predict(x_test)
y_pred

array([9.5, 9.5])

In [26]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-16.0

In [27]:
import numpy as np
car_age = np.array([[2.5]])
model.predict(car_age)

C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([9.5])

In [28]:
from sklearn.datasets import load_iris

In [29]:
data = load_iris()
data 

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [31]:
x = data.data # 'data' because of in iris 'data' is written 
y = data.target 

## To view all datasets in sklearn

In [33]:
from sklearn import datasets

print(dir(datasets))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_arff_parser', '_base', '_california_housing', '_covtype', '_kddcup99', '_lfw', '_olivetti_faces', '_openml', '_rcv1', '_samples_generator', '_species_distributions', '_svmlight_format_fast', '_svmlight_format_io', '_twenty_newsgroups', 'clear_data_home', 'data', 'descr', 'dump_svmlight_file', 'fetch_20newsgroups', 'fetch_20newsgroups_vectorized', 'fetch_california_housing', 'fetch_covtype', 'fetch_file', 'fetch_kddcup99', 'fetch_lfw_pairs', 'fetch_lfw_people', 'fetch_olivetti_faces', 'fetch_openml', 'fetch_rcv1', 'fetch_species_distributions', 'get_data_home', 'load_breast_cancer', 'load_diabetes', 'load_digits', 'load_files', 'load_iris', 'load_linnerud', 'load_sample_image', 'load_sample_images', 'load_svmlight_file', 'load_svmlight_files', 'load_wine', 'make_biclusters', 'make_blobs', 'make_checkerboard', 'make_circles', 'make_classificat

## Load load_wine dataset

In [35]:
from sklearn.datasets import load_wine
data = load_wine()
data 

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]], shape=(178, 13)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## load make regression

In [36]:
from sklearn.datasets import make_regression
data = make_regression()
data

(array([[-0.67450208, -1.08419594, -1.03117514, ..., -0.72528114,
         -1.60741593, -0.76006638],
        [ 1.56938736,  0.60326007,  0.93770745, ...,  2.56468393,
         -0.29932564,  1.61929793],
        [ 0.54870201, -1.64824926,  0.11361631, ...,  0.12091284,
         -0.27398884, -1.05694045],
        ...,
        [-0.76182037,  0.72446631, -0.54082989, ...,  0.58179453,
         -0.95852307,  1.73409705],
        [-0.66223628,  0.90747479,  0.02776441, ...,  0.64334957,
          1.45514094, -0.02785364],
        [-1.00588394, -1.00078359, -1.12599897, ..., -0.12266157,
          0.1020606 , -1.27998415]], shape=(100, 100)),
 array([  84.81629529, -324.5183506 , -196.43967936,  223.69009768,
          35.45284412, -383.05253054,  248.10024459,  114.04217429,
        -254.91349763,   35.25654957,  -49.61548825,  276.17741918,
         -51.53814185,  -29.33478001,  157.30192439,  153.45079006,
          12.07060526, -115.12545255, -401.05727007,  -95.43270919,
         -59.83

In [37]:
x,y = make_regression()
print(x)
print(y) 

[[-1.52433423e+00 -1.13937204e+00 -7.25527267e-01 ...  1.17232522e-01
   5.09350296e-01  4.23173181e-01]
 [ 1.95852400e+00  6.37734612e-01  6.32691629e-01 ... -9.90143564e-01
   1.85969536e+00  1.72463918e+00]
 [-1.35876911e-01  3.95407827e-01  7.81313508e-01 ...  2.72313374e+00
   9.46929377e-01  1.32376021e+00]
 ...
 [-3.19512937e-01 -2.28819560e-03 -8.59314164e-01 ... -6.94882623e-01
   9.67927788e-01 -3.94282006e-02]
 [-4.58298475e-01  4.19815274e-01 -1.27508822e+00 ... -2.27415800e+00
   1.03793039e+00  1.02925631e+00]
 [ 1.91364894e-01 -1.69759418e-01  4.44254543e-01 ...  1.05282761e+00
   1.11859118e+00 -9.72391727e-04]]
[ 180.75548589  155.95814283  126.31849202  -87.76110851   55.05934172
   79.78620806  378.31361157  227.96986657 -257.01588139 -371.71306111
  191.32301174   71.90734346 -191.6865273    14.99691018  154.10797267
  129.47167203   26.30813174  319.85267236  262.77552301  196.06734903
 -226.09252383 -262.70487071 -130.3530817  -126.56128957   91.13555325
    3.538